### PR TITLE
Enable tables in PDF export

### LINKED ISSUE #84: PDF Styling: html tables
HTML tables are not properly rendered in the PDF:

should be a table. (See ref: https://safetag.netlify.app/activities/network_scanning )

### PR DESCRIPTION
**Pull request by vgeorge**
Add support for markdown tables, fix #84.

### CODE REVIEW

**Review by LanesGood — CHANGES_REQUESTED** [review]
@vgeorge I'm seeing some minor errors in layout like the below:
image

In "Network Scanning"
Overlapping tables (probably adjacent?):
image

Looks like a mis-read table:
image

**Comment by LanesGood** [comment]
@vgeorge I do still see some minor rendering issues. I think this is still due to problems when there are multiple adjacent tables, or tables preceding new sections or headings:

image

**Comment by vgeorge** [comment]
@LanesGood I added a change to fix the overlapping issue. The mis-read table was happening because some formatting oddity in the markdown, after I opened and saved in the CMS it seemed to be fixed.

**Comment by LanesGood** [comment]
@vgeorge I think everything is reading correctly except for the `Network Scanning` activity for which we still have rendering issues. I know you adjusted this in the CMS - might it still need an adjustment on the PDFkit code? It's rendering correctly at http://localhost:8000/activities/network_scanning, but I still see the table rendered in the PDF as the "misread table" screenshot above.

**Comment by vgeorge** [comment]
@LanesGood I forgot to commit the updated content for network scanning in this branch, now it should work.

**Review by LanesGood — APPROVED** [review]
🚀

**Pull request merged**
