### PR TITLE
Add blank state for empty guide selection

### LINKED ISSUE #62: Empty state content in guide builder
When nothing is selected in the guide builder, the Selection panel (left side) should display the entire guide. (#56). The Selected panel (right side) should display empty state content to guide the user through the tool.

### PR DESCRIPTION
**Pull request by LanesGood**
Basic text blank state. Closes #62

### CODE REVIEW

**Comment by necoline** [comment]
This implementation looks great, however, I am using something very similar to this in the [url params pr](https://github.com/developmentseed/safetag-web/pull/102/files?file-filters%5B%5D=.js&file-filters%5B%5D=.lock#diff-7e41b55d822aa943bc2cda20e04492611df849287790ff37ebbea22b2dc692deR222) Why don't we update this after that PR has been merged so it accesses the same value?

**Comment by LanesGood** [comment]
@necoline sounds good, thanks for the suggestion.

**Review by necoline — APPROVED** [review]
@LanesGood can you double check that this looks right to you?

**Comment by LanesGood** [comment]
@necoline yes, this works well - thanks for merging in.

**Pull request merged**
